### PR TITLE
Fix post tag form appearance

### PR DESCRIPTION
**Pull request by mgjeffries**
# Description
Fix the issue where post tags still look like the are selected, even when they are just focused. 
Style the buttons on the post tag form as buttons, to make them more like the badge display of tags.
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# How Has This Been Tested?
Please describe step-by-step the process that a reviewer can follow to adequately test this PR. 
- [ ] Check that the post tag form now displays as a list of buttons
- [ ] Check that when post tags are de-selected, they immediately render in grey
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by gavinschriver — APPROVED** [review]
freak yah

**Comment by skratz17** [comment]
I guess we can get rid of the `ToggleButtonGroup`, `ToggleButton`, and `Badge` imports in `PostTagForm` now, right?

**Comment by mgjeffries** [comment]
> I guess we can get rid of the `ToggleButtonGroup`, `ToggleButton`, and `Badge` imports in `PostTagForm` now, right?

Good point! ✅

**Review by skratz17 — APPROVED** [review]
sick

**Pull request merged**
